# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-22 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animalimage',
            old_name='complaint',
            new_name='animal',
        ),
        migrations.AlterField(
            model_name='animal',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, 'Macho'), (2, 'Hembra')]),
        ),
    ]
