# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 18:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_auto_20171021_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='from_complaint',
        ),
    ]
