# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-22 00:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=1000)),
                ('case', models.SmallIntegerField(choices=[(1, 'Abandono en la calle'), (2, 'Exposición a temperaturas extremas'), (3, 'Falta de agua'), (4, 'Falta de comida'), (5, 'Violencia'), (6, 'Venta ambulante')])),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('directions', models.TextField(max_length=200, null=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'Enviado'), (2, 'En Gestión'), (3, 'Resuleta'), (4, 'Erronea')])),
                ('gender', models.SmallIntegerField(choices=[(1, 'Male'), (2, 'Female')])),
                ('wounded', models.BooleanField()),
                ('color', models.TextField(max_length=50)),
                ('animal_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaint.AnimalType')),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='complaints/')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaint.Complaint')),
            ],
        ),
    ]
