# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-22 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, 'Macho'), (2, 'Hembra')]),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='wounded',
            field=models.BooleanField(choices=[(True, 'Si'), (False, 'No')]),
        ),
    ]
