# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-22 09:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('municipality', '0001_initial'),
        ('complaint', '0002_auto_20171022_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='municipality',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='municipality.Municipality'),
            preserve_default=False,
        ),
    ]
