# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-22 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0003_complaint_municipality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='wounded',
            field=models.BooleanField(choices=[(True, 'Sí'), (False, 'No')]),
        ),
    ]
