# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0004_auto_20171022_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Reportadas'), (2, 'Consolidadas'), (3, 'Verificadas'), (4, 'Cerradas'), (5, 'Desechadas')]),
        ),
    ]
